[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.20.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
